import { defineCollection } from 'astro:content';
import { docsLoader } from '@astrojs/starlight/loaders';
import { docsSchema } from '@astrojs/starlight/schema';
// `astro/zod` rather than the `z` re-exported from `astro:content`, which is
// deprecated in Astro 7.
import { z } from 'astro/zod';

/**
 * The documentation collection.
 *
 * Starlight owns the loader and the schema: the collection must be called `docs`,
 * must use `docsLoader()`, and that loader reads `src/content/docs/` with no way to
 * point it elsewhere. Hence the doubled `docs/docs/` on disk — see the comment in
 * `astro.config.mjs`. Do not "tidy" it away.
 *
 * The node reference pages under `docs/reference/nodes/` are generated by
 * `scripts/generate-node-pages.mjs` and are not committed. Everything else here is
 * written by hand.
 */
export const collections = {
  docs: defineCollection({
    loader: docsLoader(),
    schema: docsSchema({
      extend: z.object({
        /**
         * The node this page documents, for a generated reference page.
         *
         * Lets a page state its own key rather than having it parsed back out of the
         * URL, which would break the moment a node changed category.
         */
        nodeTypeId: z.string().optional(),
      }),
    }),
  }),
};
