"""Builds one values-<locale>/ from translation tables.

Two tables per locale, because the source has two shapes:

  loc/<locale>.keys.tsv    key <TAB> text          - everything hand-written
  loc/<locale>.nodes.tsv   english <TAB> text      - the generated node strings,
                                                     keyed by their English value so
                                                     the 1029 entries collapse to the
                                                     557 distinct things they say
  loc/<locale>.plurals.tsv name:quantity <TAB> text

Anything absent falls back to values/ at runtime, which is legal and is what makes a
partial translation shippable. Run: python loc/mkloc.py es
"""
import io
import os
import re
import sys

RES = 'app/src/main/res'
APOS = chr(39)
BS = chr(92)
STRING = re.compile(r'<string name="([^"]+)"([^>]*)>(.*?)</string>', re.S)
ARRAY = re.compile(r'<string-array name="([^"]+)"[^>]*>(.*?)</string-array>', re.S)
PLURAL = re.compile(r'<plurals name="([^"]+)"[^>]*>(.*?)</plurals>', re.S)
ITEM = re.compile(r'<item[^>]*>(.*?)</item>', re.S)


def table(path):
    if not os.path.exists(path):
        return {}
    out = {}
    for line in io.open(path, encoding='utf-8'):
        line = line.rstrip('\n')
        if not line or line.startswith('#') or '\t' not in line:
            continue
        k, v = line.split('\t', 1)
        out[k] = v
    return out


def escape(text):
    """Escapes for an Android resource value. Backslash first, or it doubles the rest."""
    text = text.replace(BS, BS + BS)
    text = text.replace('&', '&amp;').replace('<', '&lt;')
    out = []
    for i, ch in enumerate(text):
        if ch == APOS and (i == 0 or text[i - 1] != BS):
            out.append(BS + APOS)
        else:
            out.append(ch)
    return ''.join(out)


def build(locale):
    keys = table('loc/%s.keys.tsv' % locale)
    nodes = table('loc/%s.nodes.tsv' % locale)
    plurals = table('loc/%s.plurals.tsv' % locale)
    out_dir = os.path.join(RES, 'values-' + locale)
    os.makedirs(out_dir, exist_ok=True)
    written = 0

    for name in sorted(os.listdir(os.path.join(RES, 'values'))):
        if not name.endswith('.xml'):
            continue
        src = io.open(os.path.join(RES, 'values', name), encoding='utf-8').read()
        lines = ['<?xml version="1.0" encoding="utf-8"?>',
                 '<!-- %s. Generated by loc/mkloc.py from loc/%s.*.tsv. -->'
                 % (locale, locale),
                 '<resources>']
        count = 0

        for key, attrs, value in STRING.findall(src):
            if 'translatable="false"' in attrs:
                continue
            text = nodes.get(value) if name == 'strings_nodes.xml' else keys.get(key)
            if text is None:
                continue
            lines.append('    <string name="%s">%s</string>' % (key, escape(text)))
            count += 1

        for key, body in ARRAY.findall(src):
            items = ITEM.findall(body)
            translated = [keys.get('%s:%d' % (key, i)) for i in range(len(items))]
            if any(t is None for t in translated):
                continue
            lines.append('    <string-array name="%s">' % key)
            lines += ['        <item>%s</item>' % escape(t) for t in translated]
            lines.append('    </string-array>')
            count += len(items)

        for key, _ in PLURAL.findall(src):
            forms = [(q, plurals['%s:%s' % (key, q)])
                     for q in ('zero', 'one', 'two', 'few', 'many', 'other')
                     if '%s:%s' % (key, q) in plurals]
            if not forms:
                continue
            lines.append('    <plurals name="%s">' % key)
            lines += ['        <item quantity="%s">%s</item>' % (q, escape(t)) for q, t in forms]
            lines.append('    </plurals>')
            count += len(forms)

        lines.append('</resources>')
        target = os.path.join(out_dir, name)
        if count == 0:
            if os.path.exists(target):
                os.remove(target)
            continue
        io.open(target, 'w', encoding='utf-8', newline='').write('\n'.join(lines) + '\n')
        written += count
        print('  %-26s %4d' % (name, count))
    missing = []
    for name in sorted(os.listdir(os.path.join(RES, 'values'))):
        if not name.endswith('.xml'):
            continue
        src = io.open(os.path.join(RES, 'values', name), encoding='utf-8').read()
        for key, attrs, value in STRING.findall(src):
            if 'translatable="false"' in attrs or key == 'app_name':
                continue
            got = nodes.get(value) if name == 'strings_nodes.xml' else keys.get(key)
            if got is None:
                missing.append(key)
    print('values-%s: %d strings, %d untranslated' % (locale, written, len(missing)))
    if missing:
        print('  missing: ' + ', '.join(missing[:12]) + ('' if len(missing) <= 12 else ' …'))


if __name__ == '__main__':
    build(sys.argv[1])
